### ISSUE TITLE
Add support of VS preview toolchain.

### ISSUE THREAD

**Issue by lordofdest** [gildor2/BuildTools#1]
BuildTools can't find my VS 2019 Preview toolchain.

Solution:
>         display_name=`"$vswhere" -latest -prerelease $version_filter -property displayName`
>         base_path=`"$vswhere" -latest -prerelease $version_filter -property installationPath`

@gildor2

**Comment by gildor2** [comment]
Probably no longer an issue, added VS 2022 support (see #2)

**Comment by avail** [comment]
this is indeed still an issue. I only have the preview version of vs2022 installed, vswhere doesn't include it unless -prerelease is specified.
` -prerelease    Also searches prereleases. By default, only releases are searched.`

Edit: can confirm, with the edit proposed in this issue it works fine.
